AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/Request/RequestCreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AM.EmergencyService.App.Web.Models.Request
{
    public class RequestCreateViewModel
    {
        [Display(Name = "Адрес вызова")]
        [Required]
        public string RequestAddress { get; set; }
        [Display(Name = "Причина вызова")]
        [Required]
        public string RequestReason { get; set; }
        [Display(Name = "Категория вызова")]
        [Required]
        public int CategoryId { get; set; }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/Request/RequestEditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AM.EmergencyService.App.Web.Models.Request
{
    public class RequestEditViewModel
    {
        [Display(Name = "Номер вызова")]
        [Required]
        public int RequestNumber { get; set; }
        [Display(Name = "Адрес вызова")]
        [Required]
        public string RequestAddress { get; set; }
        [Display(Name = "Причина вызова")]
        [Required]
        public string RequestReason { get; set; }
        [Display(Name = "Дата вызова")]
        [DataType(DataType.Date)]
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime RequestDate { get; set; }
        [Display(Name = "Категория вызова")]
        [Required]
        public int Category { get; set; }

    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/Request/RequestViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AM.EmergencyService.App.Web.Models.Request
{
    public class RequestViewModel
    {
        [Display(Name = "Номер вызова")]
        [Required]
        public int RequestNumber { get; set; }
        [Display(Name = "Адрес вызова")]
        [Required]
        public string RequestAddress { get; set; }
        [Display(Name = "Причина вызова")]
        [Required]
        public string RequestReason { get; set; }
        [Display(Name = "Дата вызова")]
        [DataType(DataType.Date)]
        [Required]
        public DateTime RequestDate { get; set; }
        [Display(Name = "Категория вызова")]
        [Required]
        public string CategoryName { get; set; }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/RequestViewModel.cs
namespace AM.EmergencyService.App.Web.Models
{
    public class RequestViewModel
    {
        public int RequestNumber { get; set; }
        public string RequestAddress { get; set; }
        public string RequestReason { get; set; }
        public string RequestDate { get; set; }
        public string CategoryName { get; set; }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/RequestController.cs
using AM.EmergencyService.App.Business.DataProvider;
using AM.EmergencyService.App.Business.Service;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Logger;
using AM.EmergencyService.App.Common.Models;
using AM.EmergencyService.App.Web.Attributes;
using AM.EmergencyService.App.Web.Models.Request;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class RequestController : Controller
    {
        private static ILogger _logger;
        private IRequestsProvider _requestsProvider;
        private ICategoriesProvider _categoriesProvider;
        private IRequestDetailsProvider _requestDetailsProvider;
        private IRequestService _requestService;

        public RequestController(IRequestService requestService, IRequestsProvider requestsProvider, ICategoriesProvider categoriesProvider, IRequestDetailsProvider requestDetailsProvider, ILogger logger)
        {
            ErrorHandlingHelper.IfArgumentNullException(categoriesProvider, "ICategoriesProvider");
            ErrorHandlingHelper.IfArgumentNullException(requestsProvider, "IRequestsProvider");
            ErrorHandlingHelper.IfArgumentNullException(requestDetailsProvider, "IRequestDetailsProvider");
            ErrorHandlingHelper.IfArgumentNullException(logger, "ILogger");
            _requestsProvider = requestsProvider;
            _categoriesProvider = categoriesProvider;
            _requestDetailsProvider = requestDetailsProvider;
            _requestService = requestService;
            _logger = logger;
        }

        public ActionResult Index()
        {
            return View();
        }
        [Dispatcher]
        public ActionResult Edit(int requestNumber)
        {
            var request = _requestsProvider.GetRequestByNumber(requestNumber, null);
            return View(ParseRequestModelToEditViewModel(request));
        }
        [HttpPost]
        public ActionResult Edit(RequestEditViewModel requestEditViewModel)
        {
            _requestService.Update(ParseEditViewModelToRequestModel(requestEditViewModel));
            return RedirectToAction("Index");
        }
        public ActionResult Search()
        {
            return View();
        }
        [Dispatcher]
        public ActionResult RequestList()
        {
            var requestList = ParseRequestListToViewModelList(_requestsProvider.GetAllData());
            return PartialView(requestList);
        }

        [Dispatcher]
        public ActionResult GetDataSearch(string SearchBy, string SearchValue, string SearchDate)
        {
            IEnumerable<RequestViewModel> requestList = new List<RequestViewModel>();

            if (!string.IsNullOrEmpty(SearchValue))
            {
                switch (SearchBy)
                {
                    case "requestNumber":
                        {
                            requestList = ParseRequestListToViewModelList(_requestsProvider.GetRequestByNumber(Int32.Parse(SearchValue), SearchDate));
                            break;
                        }
                    case "requestCategory":
                        {
                            requestList = ParseRequestListToViewModelList(_requestsProvider.GetRequestByCategory(SearchValue, SearchDate));
                            break;
                        }
                    case "requestAddress":
                        {
                            requestList = ParseRequestListToViewModelList(_requestsProvider.GetRequestByAddress(SearchValue, SearchDate));
                            break;
                        }
                }
            }
            else
            {
                return View();
            }
            return PartialView("RequestList", requestList);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(RequestCreateViewModel requestViewModel)
        {
            _requestService.Create(ParseCreateViewModelToRequestModel(requestViewModel));
            return RedirectToAction("Index");
        }
        [ChildActionOnly]
        public PartialViewResult SelectCategory()
        {
            var categoryList = _categoriesProvider.GetCategories();
            if (categoryList != null)
            {
                return PartialView(categoryList);
            }
            else
            {
                return null;
            }
        }

        #region Helpers
        private List<RequestViewModel> ParseRequestListToViewModelList(IEnumerable<RequestModel> requestList)
        {
            List<RequestViewModel> requestViewModelList = new List<RequestViewModel>();
            foreach (RequestModel request in requestList)
            {
                requestViewModelList.Add(new RequestViewModel
                {
                    RequestNumber = request.RequestNumber,
                    RequestAddress = request.RequestAddress,
                    RequestDate = request.RequestDate,
                    RequestReason = request.RequestReason,
                    CategoryName = request.Category.CategoryName
                });
            }
            return requestViewModelList;
        }
        private RequestModel ParseCreateViewModelToRequestModel(RequestCreateViewModel requestCreateViewModel)
        {
            RequestModel requestModel = new RequestModel
            {
                RequestAddress = requestCreateViewModel.RequestAddress,
                RequestReason = requestCreateViewModel.RequestReason,
                Category = new CategoryModel { Id = requestCreateViewModel.CategoryId }
            };
            return requestModel;
        }
        private RequestEditViewModel ParseRequestModelToEditViewModel(IEnumerable<RequestModel> requestModel)
        {
            RequestEditViewModel requestEditModel = new RequestEditViewModel
            {
                RequestNumber = requestModel.First().RequestNumber,
                RequestAddress = requestModel.First().RequestAddress,
                RequestReason = requestModel.First().RequestReason,
                RequestDate = requestModel.First().RequestDate,
                Category = requestModel.First().Category.Id
            };
            return requestEditModel;
        }
        private RequestModel ParseEditViewModelToRequestModel(RequestEditViewModel requestEditModel)
        {
            RequestModel requestModel = new RequestModel
            {
                RequestNumber = requestEditModel.RequestNumber,
                RequestAddress = requestEditModel.RequestAddress,
                RequestReason = requestEditModel.RequestReason,
                RequestDate = requestEditModel.RequestDate,
                Category = new CategoryModel { Id = requestEditModel.Category }
            };
            return requestModel;
        }
        #endregion
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/RequestDetailController.cs
using AM.EmergencyService.App.Business.DataProvider;
using AM.EmergencyService.App.Business.Service;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Models;
using AM.EmergencyService.App.Web.Attributes;
using AM.EmergencyService.App.Web.Models.RequestDetail;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class RequestDetailController : Controller
    {
        private IRequestDetailsProvider _requestDetailsProvider;
        private IRequestDetailService _requestDetailService;

        public RequestDetailController(IRequestDetailsProvider requestDetailsProvider, IRequestDetailService requestDetailService)
        {
            ErrorHandlingHelper.IfArgumentNullException(requestDetailsProvider, "IRequestDetailsProvider");
            ErrorHandlingHelper.IfArgumentNullException(requestDetailService, "IRequestDetailService");
            _requestDetailsProvider = requestDetailsProvider;
            _requestDetailService = requestDetailService;
        }
        [Dispatcher]
        public ActionResult Details(int requestNumber)
        {
            var incidents = _requestDetailsProvider.GetRequestDetailsByRequestNumber(requestNumber);
            return View(incidents);
        }
        [Dispatcher]
        public ActionResult Edit(int requestNumber)
        {
            var requestDetail = ParseRequestDetailModelToCreatViewModel(_requestDetailsProvider.GetRequestDetailsByRequestNumber(requestNumber));
            if (requestDetail == null)
            {
                return RedirectToAction("Create", new { requestNumber = requestNumber });
            }
            else
            {
                return View(requestDetail);
            }
        }
        [HttpPost]
        public ActionResult Edit(RequestDetailCreateViewModel viewModel)
        {
            _requestDetailService.Edit(ParseCreateViewModelToRequestDetailModel(viewModel));
            if (viewModel.CasualtyId != null)
            {
                foreach (var casualty in viewModel.CasualtyId)
                {
                    _requestDetailService.AddCasualtyToRequestDetail(viewModel.RequestNumber, casualty);
                }
            }
            if (viewModel.InventoryNumber != null)
            {
                foreach (var inventory in viewModel.InventoryNumber)
                {
                    _requestDetailService.AddInventoryToRequestDetail(viewModel.RequestNumber, inventory);
                }
            }

            return RedirectToAction("Index", "Request");
        }
        [Dispatcher]
        public ActionResult Create(int requestNumber)
        {
            RequestDetailCreateViewModel viewModel = new RequestDetailCreateViewModel { RequestNumber = requestNumber };
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(RequestDetailCreateViewModel viewModel)
        {
            _requestDetailService.Create(ParseCreateViewModelToRequestDetailModel(viewModel));
            if (viewModel.CasualtyId != null)
            {
                foreach (var casualty in viewModel.CasualtyId)
                {
                    _requestDetailService.AddCasualtyToRequestDetail(viewModel.RequestNumber, casualty);
                }
            }
            if (viewModel.InventoryNumber != null)
            {
                foreach (var inventory in viewModel.InventoryNumber)
                {
                    _requestDetailService.AddInventoryToRequestDetail(viewModel.RequestNumber, inventory);
                }
            }

            return RedirectToAction("Index", "Request");
        }

        #region PartialView
        [ChildActionOnly]
        public PartialViewResult ShowRequestDetails(int requestNumber)
        {
            ViewBag.brigadeNumber = requestNumber;
            var incident = _requestDetailsProvider.GetRequestDetailsByRequestNumber(requestNumber);
            if (incident != null)
            {
                return PartialView(ParseRequestDetailModelToViewModel(incident));
            }
            else
            {
                return null;
            }
        }
        #endregion

        #region Helper
        private RequestDetailModel ParseCreateViewModelToRequestDetailModel(RequestDetailCreateViewModel requestCreateViewModel)
        {
            RequestDetailModel requestModel = new RequestDetailModel
            {
                RequestNumber = requestCreateViewModel.RequestNumber,
                IncidentInformation = requestCreateViewModel.IncidentInformation,
                IncidentReason = requestCreateViewModel.IncidentReason,
                BrigadeArrivalDate = requestCreateViewModel.BrigadeArrivalDate,
                BrigadeCallDate = requestCreateViewModel.BrigadeCallDate,
                BrigadeEndDate = requestCreateViewModel.BrigadeEndDate,
                BrigadeNumber = requestCreateViewModel.BrigadeNumber,
                BrigadeReturnDate = requestCreateViewModel.BrigadeReturnDate
            };
            return requestModel;
        }
        private RequestDetailCreateViewModel ParseRequestDetailModelToCreatViewModel(RequestDetailModel requestDetailModel)
        {
            RequestDetailCreateViewModel requestModel = new RequestDetailCreateViewModel();
            if (requestDetailModel != null)
            {
                requestModel = new RequestDetailCreateViewModel
                {
                    RequestNumber = requestDetailModel.RequestNumber,
                    IncidentInformation = requestDetailModel.IncidentInformation,
                    IncidentReason = requestDetailModel.IncidentReason,
                    BrigadeArrivalDate = requestDetailModel.BrigadeArrivalDate,
                    BrigadeCallDate = requestDetailModel.BrigadeCallDate,
                    BrigadeEndDate = requestDetailModel.BrigadeEndDate,
                    BrigadeNumber = requestDetailModel.BrigadeNumber,
                    BrigadeReturnDate = requestDetailModel.BrigadeReturnDate
                };
            }
            else
            {
                return null;
            }
            return requestModel;
        }
        private RequestDetailViewModel ParseRequestDetailModelToViewModel(RequestDetailModel requestDetailModel)
        {
            RequestDetailViewModel requestModel = new RequestDetailViewModel
            {
                RequestNumber = requestDetailModel.RequestNumber,
                IncidentInformation = requestDetailModel.IncidentInformation,
                IncidentReason = requestDetailModel.IncidentReason,
                BrigadeArrivalDate = requestDetailModel.BrigadeArrivalDate,
                BrigadeCallDate = requestDetailModel.BrigadeCallDate,
                BrigadeEndDate = requestDetailModel.BrigadeEndDate,
                BrigadeNumber = requestDetailModel.BrigadeNumber,
                BrigadeReturnDate = requestDetailModel.BrigadeReturnDate
            };
            return requestModel;
        }
        #endregion
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/Create.cshtml
@model AM.EmergencyService.App.Web.Models.Request.RequestCreateViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RequestCreateViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestReason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestReason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestReason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("SelectCategory")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/globalize.js"></script>
<script src="~/Scripts/jquery.validate.globalize.js"></script>

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/Details.cshtml
@model IEnumerable<AM.EmergencyService.App.Common.Models.RequestDetailModel>
@{
    ViewBag.Title = "Происшествия";
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RequestNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IncidentInformation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IncidentReason)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrigadeNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrigadeCallDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrigadeArrivalDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrigadeEndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrigadeReturnDate)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RequestNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IncidentInformation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IncidentReason)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrigadeNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrigadeCallDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrigadeArrivalDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrigadeEndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrigadeReturnDate)
        </td>

        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |*@
            @Html.ActionLink("Подробнее", "Details", new { requestNumber = item.RequestNumber }) |
            @* @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
        </td>
    </tr>
    }
</table>
<p>
    @Html.ActionLink("Back to List", "Index", "Request")
</p>

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/Edit.cshtml
@model AM.EmergencyService.App.Web.Models.Request.RequestEditViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Изменение вызова</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RequestNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.RequestNumber, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestReason, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestReason, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestReason, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("SelectCategory")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/Index.cshtml
<h2>Вызовы</h2>
@Html.ActionLink("Добавить вызов", "Create", "Request")
<div>
    @Html.Action("RequestList")
</div>
   

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/RequestList.cshtml
@model IEnumerable<AM.EmergencyService.App.Web.Models.Request.RequestViewModel>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RequestNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestReason)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestReason)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
                <td>
                    @Html.ActionLink("Изменить", "Edit", "Request", new { requestNumber = item.RequestNumber }, null) |
                    @Html.ActionLink("Подробнее", "Details", "RequestDetail", new { requestNumber = item.RequestNumber }, null)
                </td>
            </tr>
        }
    </table>
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/Search.cshtml
@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "searchForm" }))
{
    <fieldset class="col-md-6">
        <legend>Фильтр: </legend>
        @Html.Label("Дата вызова", htmlAttributes: new { @class = "control-label col-md-3" })
        @Html.TextBox("requestDate", "", new { @class = "form-control datepicker", @type="date" })
        @Html.RadioButton("filter", "requestNumber", true) Поиск по номеру вызова
        <br>
        @Html.RadioButton("filter", "requestCategory") Поиск по категории вызова
        <br>
        @Html.RadioButton("filter", "requestAddress") Поиск по адресу вызова
        <br>
        @Html.TextBox("searchString")
        <p><input type="button" value="Поиск" id="searchBtn"></p>
    </fieldset>
}
<div id="DataSearching">
    @*partial view content*@
</div>
@section Scripts {
    @*<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>*@
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/DateTimePickerScript.js"></script>
    <script src="~/Scripts/DataSearchingScript.js"></script>
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/SelectCategory.cshtml
@model IEnumerable<AM.EmergencyService.App.Common.Models.CategoryModel>

<div>
    @Html.DropDownList("CategoryId", new SelectList(Model, "Id", "CategoryName"), new { @class = "form-control" })
</div>

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Request/_searchPartialView.cshtml
@model IEnumerable<AM.EmergencyService.App.Web.Models.RequestViewModel>
@if (Model != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RequestNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestReason)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryName)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestAddress)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestReason)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CategoryName)
                </td>
            </tr>
        }
    </table>
}