AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/Brigade/BrigadeCreateViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AM.EmergencyService.App.Web.Models.Brigade
{
    public class BrigadeCreateViewModel
    {
        [Display(Name = "Номер бригады")]
        [Required]
        public int BrigadeNumber { get; set; }
        [Display(Name = "Члены бригады")]
        [Required]
        public List<int> RescuerId { get; set; }
        [Display(Name = "Инвентарь бригады")]
        [Required]
        public List<int> InventoryNumber { get; set; }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Models/Brigade/BrigadeViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AM.EmergencyService.App.Web.Models.Brigade
{
    public class BrigadeViewModel
    {
        [Display(Name = "Номер бригады")]
        [Required]
        public int BrigadeNumber { get; set; }
        [Display(Name = "Дата")]
        [Required]
        public DateTime Date { get; set; }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/BrigadeController.cs
using AM.EmergencyService.App.Business.DataProvider;
using AM.EmergencyService.App.Business.Service;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Models;
using AM.EmergencyService.App.Web.Attributes;
using AM.EmergencyService.App.Web.Models.Brigade;
using AM.EmergencyService.App.Web.Models.Rescuers;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class BrigadeController : Controller
    {
        private IBrigadesProvider _brigadesProvider;
        private IBrigadeService _brigadeService;
        private IRescuersProvider _rescuersProvider;
        private IInventoryProvider _inventoryProvider;

        public BrigadeController(IBrigadesProvider brigadesProvider, IBrigadeService brigadeService, IRescuersProvider rescuersProvider, IInventoryProvider inventoryProvider)
        {
            ErrorHandlingHelper.IfArgumentNullException(brigadesProvider, "IBrigadesProvider");
            ErrorHandlingHelper.IfArgumentNullException(rescuersProvider, "IRescuersProvider");
            ErrorHandlingHelper.IfArgumentNullException(inventoryProvider, "IInventoryProvider");
            ErrorHandlingHelper.IfArgumentNullException(brigadeService, "IBrigadeService");
            _brigadeService = brigadeService;
            _brigadesProvider = brigadesProvider;
            _rescuersProvider = rescuersProvider;
            _inventoryProvider = inventoryProvider;
        }
        [Editor]
        public ActionResult Index()
        {
            var brigades = _brigadesProvider.GetBrigadeByDate(DateTime.Now);
            return View(brigades);
        }
        [Dispatcher]
        public ActionResult Details(int brigadeNumber, DateTime date)
        {
            var ViewModel = new BrigadeViewModel
            {
                BrigadeNumber=brigadeNumber,
                Date=date
            };
            return View(ViewModel);
        }
        [Editor]
        public ActionResult Create()
        {
            var ViewModel = new BrigadeCreateViewModel
            {
                InventoryNumber = new List<int>(),
                RescuerId = new List<int>()
            };
            return View(ViewModel);
        }
        [HttpPost]
        public ActionResult Create(BrigadeCreateViewModel brigadeCreateViewModel)
        {
            if (brigadeCreateViewModel.RescuerId != null)
            {
                foreach (var rescuer in brigadeCreateViewModel.RescuerId)
                {
                    _brigadeService.AddRescuersBrigade(brigadeCreateViewModel.BrigadeNumber, rescuer);
                }
            }
            if (brigadeCreateViewModel.InventoryNumber != null)
            {
                foreach (var inventory in brigadeCreateViewModel.InventoryNumber)
                {
                    _brigadeService.AddInventoryBrigade(brigadeCreateViewModel.BrigadeNumber, inventory);
                }
            }
            return RedirectToAction("Index");
        }
        [Editor]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(BrigadeModel brigadeModel)
        {
            _brigadeService.Add(brigadeModel);
            return RedirectToAction("Index");
        }
        [Editor]
        public ActionResult Edit(int brigadeNumber)
        {
            var ViewModel = new BrigadeCreateViewModel
            {
                BrigadeNumber=brigadeNumber,
                InventoryNumber = new List<int>(),
                RescuerId = new List<int>()
            };
            return View(ViewModel);
        }
       
        #region PartialView
        public PartialViewResult SelectBrigade()
        {
            var brigadeList = _brigadesProvider.GetAllData();
            if (brigadeList != null)
            {
                return PartialView(brigadeList);
            }
            else
            {
                return null;
            }
        }
        #endregion

        #region Helpers
        private List<RescuerSelectViewModel> ToRescuerViewModel(IEnumerable<RescuerModel> rescuers)
        {
            List<RescuerSelectViewModel> rescuersViewModel = new List<RescuerSelectViewModel>();
            foreach (var rescuer in rescuers)
            {
                rescuersViewModel.Add(new RescuerSelectViewModel
                {
                    Id = rescuer.Id,
                    Name = rescuer.Job + " " + rescuer.Surname + " " + rescuer.Firstname + " " + rescuer.Lastname
                });
            }
            return rescuersViewModel;
        }
        #endregion
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/InventoryController.cs
using AM.EmergencyService.App.Business.DataProvider;
using AM.EmergencyService.App.Business.Service;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Models;
using AM.EmergencyService.App.Web.Attributes;
using AM.EmergencyService.App.Web.Models.Inventory;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class InventoryController : Controller
    {
        private IInventoryProvider _inventoryProvider;
        private IInventoryService _inventoryService;
        public InventoryController(IInventoryProvider inventoryProvider, IInventoryService inventoryService)
        {
            ErrorHandlingHelper.IfArgumentNullException(inventoryProvider, "IInventoryProvider");
            ErrorHandlingHelper.IfArgumentNullException(inventoryService, "IInventoryService");
            _inventoryService = inventoryService;
            _inventoryProvider = inventoryProvider;
        }
        public ActionResult Index()
        {
            var inventoryList = _inventoryProvider.GetAllData();
            return View(inventoryList);
        }
        [Editor]
        public ActionResult Create()
        {
            var inventory = new InventoryModel();
            return View(inventory);
        }
        [Editor]
        [HttpPost]
        public ActionResult Create(InventoryModel inventory)
        {
            _inventoryService.Create(inventory);
            return RedirectToAction("Index");
        }
        [Editor]
        public ActionResult Edit(int inventoryNumber)
        {
            var inventory = _inventoryProvider.GetInventoryByNumber(inventoryNumber);
            return View(inventory);
        }
        [HttpPost]
        public ActionResult Edit(InventoryModel inventoryModel)
        {
            _inventoryService.Edit(inventoryModel);
            return RedirectToAction("Index");
        }
        [Editor]
        public ActionResult DeleteInventoryFromBrigade(int brigadeNumber, int inventoryNumber)
        {
            _inventoryService.DeleteInventoryFromBrigade(brigadeNumber, inventoryNumber);
            return RedirectToAction("Details", "Brigade", new { brigadeNumber = brigadeNumber });
        }
        [Dispatcher]
        public ActionResult DeleteInventoryFromRequest(int requestNumber, int inventoryNumber)
        {
            _inventoryService.DeleteInventoryFromRequest(requestNumber, inventoryNumber);
            return RedirectToAction("Details", "RequestDetail", new { requestNumber = requestNumber });
        }

        #region PartialViews
        [ChildActionOnly]
        public PartialViewResult SelectInventory(int requestNumber)
        {
            IEnumerable<InventoryModel> inventoryList = null;
            if (requestNumber < 0)
            {
                inventoryList = _inventoryProvider.GetAllData();
            }
            else
            {
                inventoryList = _inventoryProvider.GetInventoryNotInRequest(requestNumber);

            }
            if (inventoryList != null)
            {
                return PartialView(inventoryList);
            }
            else
            {
                return null;
            }
        }
        [ChildActionOnly]
        public PartialViewResult ShowBrigadeInventory(int brigadeNumber, DateTime date)
        {
            ViewBag.brigadeNumber = brigadeNumber;
            var inventoryList = _inventoryProvider.GetInventoryByBrigadeNumber(brigadeNumber, date);
            if (inventoryList != null)
            {
                return PartialView(ToInventoryViewModel(inventoryList));
            }
            else
            {
                return null;
            }
        }
        [ChildActionOnly]
        public PartialViewResult ShowRequestInventory(int requestNumber)
        {
            ViewBag.requestNumber = requestNumber;
            var inventoryList = _inventoryProvider.GetInventoryByRequestNumber(requestNumber);
            if (inventoryList != null)
            {
                return PartialView(ToInventoryViewModel(inventoryList));
            }
            else
            {
                return null;
            }
        }
        #endregion
        #region Helpers
        private List<InventoryViewModel> ToInventoryViewModel(IEnumerable<InventoryModel> inventoryList)
        {
            List<InventoryViewModel> inventoryViewModel = new List<InventoryViewModel>();
            foreach (var inventory in inventoryList)
            {
                inventoryViewModel.Add(new InventoryViewModel
                {
                    InventoryNumber = inventory.InventoryNumber,
                    InventoryName = inventory.InventoryName
                });
            }
            return inventoryViewModel;
        }
        #endregion
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/RescuersController.cs
using AM.EmergencyService.App.Business.DataProvider;
using AM.EmergencyService.App.Business.Service;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Models;
using AM.EmergencyService.App.Web.Attributes;
using AM.EmergencyService.App.Web.Models.Rescuers;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class RescuersController : Controller
    {
        private IRescuersProvider _rescuersProvider;
        private IRescuersService _rescuerService;
        public RescuersController(IRescuersProvider rescuersProvider, IRescuersService rescuerService)
        {
            ErrorHandlingHelper.IfArgumentNullException(rescuersProvider, "IRescuersProvider");
            ErrorHandlingHelper.IfArgumentNullException(rescuerService, "IRescuersService");
            _rescuerService = rescuerService;
            _rescuersProvider = rescuersProvider;
        }
        // GET: Rescuers
        [Editor]
        public ActionResult Index()
        {
            var rescuersList = _rescuersProvider.GetAllData();
            return View(ToRescuerViewModel(rescuersList));
        }
        [Editor]
        public ActionResult Edit(int rescuerId)
        {
            var rescuerList = _rescuersProvider.GetRescuerById(rescuerId);
            return View(ParseRescuerModelToViewModel(rescuerList));
        }
        [HttpPost]
        public ActionResult Edit(RescuerViewModel rescuerModel)
        {
            _rescuerService.Edit(ParseViewModelToRescuerModel(rescuerModel));
            return RedirectToAction("Index");
        }
        [Editor]
        public ActionResult DeleteRescuerFromBrigade(int brigadeNumber, int rescuerId)
        {
            _rescuerService.DeleteRescuerFromBrigade(brigadeNumber, rescuerId);
            return RedirectToAction("Details", "Brigade", new { brigadeNumber = brigadeNumber });
        }
        public ActionResult Create()
        {
            RescuerCreateViewModel viewModel = new RescuerCreateViewModel();
            return View(viewModel);
        }
        [HttpPost]
        public ActionResult Create(RescuerCreateViewModel model)
        {
            _rescuerService.Add(ParseToRescuerModel(model));
            return RedirectToAction("Index");
        }
        #region PartialViews
        [ChildActionOnly]
        public PartialViewResult SelectRescuers()
        {
            var rescuerList = ToRescuerSelectViewModel(_rescuersProvider.GetAllData());
            if (rescuerList != null)
            {
                return PartialView(rescuerList);
            }
            else
            {
                return null;
            }
        }
        [ChildActionOnly]
        public PartialViewResult ShowBrigadeRescuers(int brigadeNumber, DateTime date)
        {
            ViewBag.brigadeNumber = brigadeNumber;
            var rescuerList = _rescuersProvider.GetRescuersByBrigadeNumber(brigadeNumber, date);
            if (rescuerList != null)
            {
                return PartialView(rescuerList);
            }
            else
            {
                return null;
            }
        }
        #endregion

        #region Helpers
        private List<RescuerSelectViewModel> ToRescuerSelectViewModel(IEnumerable<RescuerModel> rescuers)
        {
            List<RescuerSelectViewModel> rescuersViewModel = new List<RescuerSelectViewModel>();
            foreach (var rescuer in rescuers)
            {
                rescuersViewModel.Add(new RescuerSelectViewModel
                {
                    Id = rescuer.Id,
                    Name = rescuer.Job + " " + rescuer.Surname + " " + rescuer.Firstname + " " + rescuer.Lastname
                });
            }
            return rescuersViewModel;
        }
        private List<RescuerViewModel> ToRescuerViewModel(IEnumerable<RescuerModel> rescuers)
        {
            List<RescuerViewModel> rescuersViewModel = new List<RescuerViewModel>();
            foreach (var rescuer in rescuers)
            {
                rescuersViewModel.Add(new RescuerViewModel
                {
                    Id = rescuer.Id,
                    Firstname = rescuer.Firstname,
                    Surname = rescuer.Surname,
                    Lastname = rescuer.Lastname,
                    BirthDate = rescuer.BirthDate,
                    Job = rescuer.Job
                });
            }
            return rescuersViewModel;
        }

        private RescuerModel ParseToRescuerModel(RescuerCreateViewModel rescuer)
        {
            RescuerModel rescuerModel = new RescuerModel();

            rescuerModel = new RescuerModel
            {
                Firstname = rescuer.Firstname,
                Surname = rescuer.Surname,
                Lastname = rescuer.Lastname,
                BirthDate = rescuer.BirthDate,
                Job = rescuer.Job
            };
            return rescuerModel;
        }
        private RescuerModel ParseViewModelToRescuerModel(RescuerViewModel rescuer)
        {
            RescuerModel rescuerModel = new RescuerModel();

            rescuerModel = new RescuerModel
            {
                Id=rescuer.Id,
                Firstname = rescuer.Firstname,
                Surname = rescuer.Surname,
                Lastname = rescuer.Lastname,
                BirthDate = rescuer.BirthDate,
                Job = rescuer.Job
            };
            return rescuerModel;
        }
        private RescuerViewModel ParseRescuerModelToViewModel(RescuerModel rescuer)
        {
            RescuerViewModel rescuerModel = new RescuerViewModel();

            rescuerModel = new RescuerViewModel
            {
                Id = rescuer.Id,
                Firstname = rescuer.Firstname,
                Surname = rescuer.Surname,
                Lastname = rescuer.Lastname,
                BirthDate = rescuer.BirthDate,
                Job = rescuer.Job
            };
            return rescuerModel;
        }
        #endregion
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/Add.cshtml
@model AM.EmergencyService.App.Common.Models.BrigadeModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Создание новой бригады</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Номер бригады", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BrigadeNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrigadeNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/Create.cshtml
@model AM.EmergencyService.App.Web.Models.Brigade.BrigadeCreateViewModel

@{
    ViewBag.Title = "Сформировать бригаду";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сформировать бригаду</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.BrigadeNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("SelectBrigade")
                @Html.ActionLink("Добавить новую бригаду", "Add", "Brigade")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RescuerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("SelectRescuers", "Rescuers")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InventoryNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("SelectInventory", "Inventory", new { requestNumber = -1 })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить бригаду" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/Details.cshtml
@model AM.EmergencyService.App.Web.Models.Brigade.BrigadeViewModel
<h4>Состав бригады:</h4>
@Html.Action("ShowBrigadeRescuers", "Rescuers", new { brigadeNumber = Model.BrigadeNumber, date = Model.Date })
<h4>Инструмент бригады:</h4>
@Html.Action("ShowBrigadeInventory", "Inventory", new { brigadeNumber = Model.BrigadeNumber, date = Model.Date })
<p>
    @Html.ActionLink("Назад", "Index")
</p>

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/Edit.cshtml
@model AM.EmergencyService.App.Web.Models.Brigade.BrigadeCreateViewModel
@using (Html.BeginForm("Create", "Brigade", FormMethod.Post))
{
    <h4>
        Состав бригады @Html.TextBoxFor(model => model.BrigadeNumber, htmlAttributes: new { style = "width:40px; height:25px;", @readonly = true }):
    </h4>
    @Html.Action("ShowBrigadeRescuers", "Rescuers", new { brigadeNumber = Model.BrigadeNumber })
    <h6>Добавить людей в бригаду:</h6>
    @Html.Action("SelectRescuers", "Rescuers")
    <h4>
        Инструмент бригады @Html.TextBoxFor(model => model.BrigadeNumber, htmlAttributes: new { style = "width:40px; height:25px;", @readonly = true }):
    </h4>
    @Html.Action("ShowBrigadeInventory", "Inventory", new { brigadeNumber = Model.BrigadeNumber })
    <h6>Добавить инвентарь в бригаду:</h6>
    @Html.Action("SelectInventory", "Inventory", new { requestNumber = -1 })
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
}
<p>
    @Html.ActionLink("Назад", "Index")
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/Index.cshtml
@model IEnumerable<AM.EmergencyService.App.Common.Models.BrigadeModel>
@{
    ViewBag.Title = "Бригады";
}
<table class="table">
    <tr>
        <th>
            @Html.Label("Номер бригады")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BrigadeNumber)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { brigadeNumber = item.BrigadeNumber }) |
                @Html.ActionLink("Подробнее", "Details", new { brigadeNumber = item.BrigadeNumber }) |
               @* @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@
            </td>
        </tr>
    }

</table>
@Html.ActionLink("Сформировать бригаду", "Create")

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Brigade/SelectBrigade.cshtml
@model IEnumerable<AM.EmergencyService.App.Common.Models.BrigadeModel>
<div>
    @Html.DropDownList("BrigadeNumber", new SelectList(Model, "BrigadeNumber", "BrigadeNumber"), new { @class = "form-control" })
</div>