AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/AdvertisingController.cs
using AM.EmergencyService.App.Business.AdProvider;
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Data.AdServiceReference;
using System.Collections.Generic;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class AdvertisingController : Controller
    {
        private const int NUM_OF_AD = 3;

        private IAdProvider _adProvider;
        public AdvertisingController(IAdProvider adProvider)
        {
            ErrorHandlingHelper.IfArgumentNullException(adProvider, "IAdProvider");
            _adProvider = adProvider;
        }
        public PartialViewResult ShowAdvertising()
        {
            var listOfAd = _adProvider.GetAd(NUM_OF_AD);
            if (listOfAd==null)
            {
                return PartialView("NoAdvertising");
            }
            else
            {
                return PartialView(listOfAd);
            }
        }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Controllers/HomeController.cs
using AM.EmergencyService.App.Common.Helper;
using AM.EmergencyService.App.Common.Logger;
using System.Web.Mvc;

namespace AM.EmergencyService.App.Web.Controllers
{
    public class HomeController : Controller
    {
        private static ILogger _logger;

        public HomeController(ILogger logger)
        {
            ErrorHandlingHelper.IfArgumentNullException(logger, "ILogger");
            _logger = logger;
        }
        public ActionResult Index(string requestDate = "")
        {
            _logger.Log(LogLevel.Info, "Application HomePage is running.");
                return View();
        }
    }
}

AM.EmergencyService.App/AM.EmergencyService.App.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <article class="col-md-8 article">
        Добро пожаловать на сайт "диспетчер МЧС". Данное веб-приложение позволяет диспетчеру МЧС
        работать с данными о вызовах, бригадах, технических средствах и прочим.
        <br>
        Данное приложение  обладает средствами навигации по категории вызова для текущей даты, а так же
        страницей поиска по параметрам: <br>
        <ul>
            <li>по номеру вызова</li>
            <li>по категории вызова</li>
            <li>по адресу</li>
        </ul>
        Веб-приложение разработнао в рамках учебного проекта "ASP.NET MVC trainig" EPAM 2018
        <br>
    </article>
    <aside class="col-md-4">
        @Html.Action("ShowAdvertising", "Advertising")
    </aside>
</div>